2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164010-bdrs4khy/logs/debug.log
2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164010-bdrs4khy/logs/debug-internal.log
2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:40:10,117 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:40:10,122 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:40:10,122 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:40:10,123 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:40:10,124 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:40:10,157 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:40:10,275 ERROR   MainThread:59405 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-05-08 16:40:58,620 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164058-jbzji0qg/logs/debug.log
2025-05-08 16:40:58,621 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164058-jbzji0qg/logs/debug-internal.log
2025-05-08 16:40:58,621 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:40:58,621 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:40:58,621 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:40:58,621 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:40:58,626 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:40:58,626 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:40:58,627 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:40:58,628 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:40:58,665 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:42:28,944 ERROR   MainThread:59405 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-05-08 16:44:21,109 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164421-0rmcs1ro/logs/debug.log
2025-05-08 16:44:21,109 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164421-0rmcs1ro/logs/debug-internal.log
2025-05-08 16:44:21,110 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:44:21,110 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:44:21,110 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:44:21,110 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:44:21,115 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:44:21,115 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:44:21,117 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:44:21,117 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:44:21,171 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:44:21,290 ERROR   MainThread:59405 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-05-08 16:44:31,410 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164431-9icpt1zu/logs/debug.log
2025-05-08 16:44:31,411 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164431-9icpt1zu/logs/debug-internal.log
2025-05-08 16:44:31,412 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:44:31,412 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:44:31,412 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:44:31,412 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:44:31,419 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:44:31,420 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:44:31,421 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:44:31,422 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:44:31,472 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:45:51,604 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:45:55,138 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164555-51nmbe36/logs/debug.log
2025-05-08 16:45:55,138 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164555-51nmbe36/logs/debug-internal.log
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:45:55,143 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:45:55,144 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:45:55,145 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:45:55,146 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:45:55,176 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:46:04,570 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:46:16,651 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164616-4t691f5f/logs/debug.log
2025-05-08 16:46:16,651 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164616-4t691f5f/logs/debug-internal.log
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:46:16,657 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:46:16,657 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:46:16,659 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:46:16,659 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:46:16,689 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:47:28,105 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:47:43,666 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164743-8krcquxo/logs/debug.log
2025-05-08 16:47:43,668 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164743-8krcquxo/logs/debug-internal.log
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:47:43,674 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:47:43,675 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:47:43,676 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:47:43,677 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:47:43,706 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:48:09,489 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
